/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BlackJack.view;

import BlackJack.model.Card;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Álvaro
 */
public class BlackJackGUI extends javax.swing.JDialog {

    
    public BlackJackGUI() {
        super(new java.awt.Frame(), true);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void getWinners(List<Card> player1, List<Card> player2, List<Card> player3, List<Card> crupier, List<Card> deck){
        List<String> result = new ArrayList<>();
        int player1result = Card.checkCards(player1);
        int player2result = Card.checkCards(player2);
        int player3result = Card.checkCards(player3);
        int crupierresult = Card.checkCards(crupier);
        
        if ((player1result > crupierresult && player1result <= 21) || (crupierresult > 21 && player1result <= 21)){
            result.add("Player1");
        }
        
        if ((player2result > crupierresult && player2result <= 21) || (crupierresult > 21 && player2result <= 21)){
            result.add("Player2");
        }
        
        if ((player3result > crupierresult && player3result <= 21) || (crupierresult > 21 && player3result <= 21)){
            result.add("Player3");
        }
        
        this.player1Text.setText("Player1: " + player1 + " " + player1result);
        this.player2Text.setText("Player2: " + player2 + " " + player2result);
        this.player3Text.setText("Player3: " + player3 + " " + player3result);
        this.crupierText.setText("Crupier: " + crupier + " " + crupierresult);
        this.deckText.setText("Deck: " + deck);
        
        this.winnersText.setText("" + result);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Text = new javax.swing.JLabel();
        player2Text = new javax.swing.JLabel();
        player3Text = new javax.swing.JLabel();
        crupierText = new javax.swing.JLabel();
        deckText = new javax.swing.JLabel();
        winnersText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1Text, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(player2Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player3Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crupierText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deckText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(winnersText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(player1Text)
                .addGap(18, 18, 18)
                .addComponent(player2Text)
                .addGap(18, 18, 18)
                .addComponent(player3Text)
                .addGap(18, 18, 18)
                .addComponent(crupierText)
                .addGap(18, 18, 18)
                .addComponent(deckText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(winnersText)
                .addGap(201, 201, 201))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crupierText;
    private javax.swing.JLabel deckText;
    private javax.swing.JLabel player1Text;
    private javax.swing.JLabel player2Text;
    private javax.swing.JLabel player3Text;
    private javax.swing.JLabel winnersText;
    // End of variables declaration//GEN-END:variables
}
